### PR TITLE
Hotfix: Schema, Example, and Context Fixes

### PR DESCRIPTION
**Pull request by sebbader-sap**

### CODE REVIEW

**Comment by sebbader-sap** [comment]
@mkollenstart I need help to push the files into the releases folder. We have an Action for it, don't we?

**Review by jimmarino — APPROVED** [review]

**Comment by mkollenstart** [comment]
No there isn't an action to create the release folder structure, since it also should be pushed in the repository.

So to create the release folder you need to execute the following commands and then push again:
```
rsync -Rav --prune-empty-dirs --exclude="releases/**" --include="*/" --include="**/*.json" --exclude="**" ./ ./releases/2024-1/
rsync -Rav --prune-empty-dirs --exclude="releases/**" --include="*/" --include="**/*.ttl" --exclude="**" ./ ./releases/2024-1/
```

But since this will overwrite the existing release folder, you have to remove the existing 2024-1 folder in releases before executing the rsync commands.

An other issue that will come up is the "Prevent Changes to Release Files" check that is executed, since this one will fail if files are modified in the releases folder. I'm not sure how we tackled that in the previous hotfix.

**Comment by sebbader-sap** [comment]
> So to create the release folder you need to execute the following commands and then push again:

Just did so

**Review by mkollenstart — APPROVED** [review]

**Comment by IgorBalog-Eng** [comment]
Nice work.
Still some small remarks, catalog and dataset have same ids (catalog.json and dataset.json, in example folder), and in catalog.json, dataset.id = policy.id
Could we use, for some future documentation, ids like urn:uuid:catalog_id_uuid, urn:uuid:dataset_id_uuid, and such?
Hoping this will not confuse readers to replace *catalog_id_uuid* with generated UUID. This way, we could use symbolic values for ids and reference them where needed.

### 2.1 Contract Request Message

|                     |                                                                                                                                         |
|---------------------|-----------------------------------------------------------------------------------------------------------------------------------------|
| **Sent by**         | [Consumer](../model/terminology.md#consumer)                                                                                            |
| **Resulting state** | `REQUESTED`, `TERMINATED`                                                                                                               |
| **Response**        | [ACK](#31-ack---contract-negotiation) or [ERROR](#32-error---contract-negotiation-error)                                                |
| **Schema**          | [TTL Shape](./message/shape/contract-request-message-shape.ttl), [JSON Schema](./message/schema/contract-request-message-schema.json)   |
| **Example**         | Initiating [Message](./message/example/contract-request-message_initial.json), [Message](./message/example/contract-offer-message.json) <---- THIS ONE here, offer| 
Message still points to contract offer message.

I will double check once again official version of documentation.

**Pull request merged**
