### PR TITLE
Pull messages as transition triggers into edges of "contract negotiation state machine"

### PR DESCRIPTION
**Pull request by SebastianOpriel**
Enhances and obeys comments of https://github.com/International-Data-Spaces-Association/ids-specification/pull/137

1st Iteration (a. without termination edges b. abbreviated msg + triggers in edges)
image
2nd Iteration (a. [with termination edges](https://github.com/International-Data-Spaces-Association/ids-specification/pull/43) b. msg + triggers in edges)
image

### CODE REVIEW

**Comment by SebastianOpriel** [comment]
# Missing
- [ ] Adjustment of transfer state machine (blocked -> first discuss PR)

**Comment by SebastianOpriel** [comment]
I agree with you. What about 1b without all edges to TERMINATED?

**Comment by jimmarino** [comment]
> I agree with you. What about 1b without all edges to TERMINATED?

Does 1.b. have the message types in it? It looks like it doesn't. It should have the message types.

**Comment by SebastianOpriel** [comment]
You are right. Here is the result: 
image
I think we have 2 valid options
- Go with @juliapampus's approach, having all edges and all states in the diagram. Only thing is that messages in nodes might not comply with UML notation
- Go with messages on edges + all edges to TERMINATED - with the downside that it is complicated to read, but correct
I would not suggest to go with the approach, now checked in, as it is IMO easier to read, but needs also the message in TERMINATED state, since the other edges were left out.

**Pull request closed without merging**
