### PR TITLE
chore: add relations for TERMINATED in state diagrams

### LINKED ISSUE #42: Add transitions to state TERMINATED
From the state diagrams, without additional text, it is not possible to derive from which states one can get into `TERMINATED`

### PR DESCRIPTION
**Pull request by juliapampus**
I know this makes it less clear, but actually more correct. WDYT?

Closes #42

### CODE REVIEW

**Review by ssteinbuss — APPROVED** [review]

**Review by ssteinbuss — CHANGES_REQUESTED** [review]
* Please check back with #71 and include the new names from #71 here
* Please include a certain degree of freedom in the initial states

**Comment by matgnt** [comment]
Another option for better readability could be to not add the state changes to the picture, but only to the text, like "all states can transition to terminated" (or similar...). I think it is easier to read the picture without all the "terminated" transitions.

**Comment by juliapampus** [comment]
Agreed on 30.03.: At the beginning, both parties can transition to `TERMINATED`, towards the end, it becomes stricter

**Comment by juliapampus** [comment]
@ssteinbuss This needs your approval.

**Review by ssteinbuss — APPROVED** [review]

**Pull request merged**
